"""user_course

Revision ID: 1e9ef98e0593
Revises: 81dfbaa3e9e5
Create Date: 2023-02-25 22:45:05.879746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9ef98e0593'
down_revision = '81dfbaa3e9e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_course',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('enrolled_courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrolled_courses',
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('enrolled_course_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['enrolled_course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], )
    )
    op.drop_table('user_course')
    # ### end Alembic commands ###
