"""empty message

Revision ID: 43e1e114e956
Revises: 1e9ef98e0593
Create Date: 2023-04-15 11:24:36.024217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e1e114e956'
down_revision = '1e9ef98e0593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hasGeneratedRelatedCourses', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_course_timestamp')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_course_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('hasGeneratedRelatedCourses')

    # ### end Alembic commands ###
